{'afghanistan': 'AFG',
            'albania': 'ALB',
             'algeria': 'DZA',
             'andorra': 'AND',
             'angola':'AGO',
             'anguilla': 'GBR',
             'antigua and barbuda': 'ATG',
             'argentina': 'ARG',
             'armenia': 'ARM',
             'aruba': 'ARW',
             'australia': 'AUS',
             'austria': 'AUT',
             'azerbaijan': 'AZE',
             'bahamas': 'BHS',
             'bahrain': 'BHR',
             'bangladesh': 'BGD',
             'barbados': 'BRB',
             'belarus': 'BLR',
             'belgium': 'BEL',
             'belize': 'BLZ',
             'benin': 'BEN',
             'bermuda': 'BMU',
             'bhutan': 'BTN',
             'bolivia': 'BOL',
             'bosnia and herzegovina': 'BIH',
             'botswana':'BWA',
             'brazil': 'BRA',
             'british virgin islands': 'VGB',
             'brunei' : 'BRN',
             'bulgaria' : 'BGR',
             'burkina faso': 'BFA',
             'burma myanmar' : 'MMR',
             'burundi': 'BDI',
             'cambodia' :'KHM',
             'cameroon': 'CMR',
             'canada': 'CAN',
             'cape verde': 'CPV',
             'cayman islands': 'CYM',
             'central african republic': 'CAF',
             'chad': 'TCD',
             'chile': 'CHL',
             'china': 'CHN',
             'colombia': 'COL',
             'comoros': 'COM',
             'costa rica':'CRI',
             "cote d'ivoire": 'CIV',
             'croatia':'HRV',
             'cuba': 'CUB',
             'cyprus': 'CYP',
             'czech republic' : 'CZE',
             'czechoslovakia' : 'CZE',
             'democratic republic of congo': 'COD',
             'denmark': 'DNK',
             'dependant territory' : 'NA',
             'dominica': 'DMA',
             'dominican republic': 'DOM',
             'ecuador': 'ECU',
             'egypt': 'EGY',
             'el salvador': 'SLV',
             'equatorial guinea': 'GNQ',
             'eritrea' : 'ERI',
             'estonia' : 'EST',
             'ethiopia' : 'ETH',
             'fiji' : 'FJI',
             'finland': 'FIN',
             'france': 'FRA',
             'gabon': 'GAB',
             'gambia': 'GMB',
             'georgia': 'GEO',
             'germany': 'DEU',
             'ghana': 'GHA',
             'greece': 'GRC',
             'grenada': 'GRD',
             'guatemala': 'GTM',
             'guinea': 'GIN',
             'guinea-bissau': 'GNB',
             'guyana': 'GUY',
             'haiti': 'HTI',
             'honduras': 'HND',
             'hong kong': 'HKG',
             'hungary': 'HUN',
             'iceland': 'ISL',
             'india': 'IND',
             'indonesia': 'IDN',
             'iran': 'IRN',
             'iraq': 'IRQ',
             'ireland': 'IRL',
             'israel': 'ISR',
             'italy': 'ITA',
             'ivory coast': 'CIV',
             'jamaica': 'JAM',
             'japan': 'JPN',
             'jordan': 'JOR',
             'kazakhstan': 'KAZ',
             'kenya': 'KEN',
             'kiribati' : 'KIR',
             'kosovo': 'XKX',
             'kuwait': 'KWT',
             'kyrgyzstan': 'KGZ',
             'laos': 'LAO',
             'latvia': 'LVA',
             'lebanon' : 'LBN',
             'lesotho': 'LSO',
             'liberia': 'LBR',
             'libya': 'LBY',
             'liechtenstein': 'LIE',
             'lithuania': 'LTU',
             'luxembourg': 'LUX',
             'macau': 'MAC',
             'macedonia': 'MKD',
             'madagascar': 'MDG',
             'malawi': 'MWI',
             'malaysia': 'MYS',
             'maldives': 'MDV',
             'mali': 'MLI',
             'malta': 'MLT',
             'marshall islands': 'MHL',
             'mauritania': 'MRT',
             'mauritius': 'MUS',
             'mexico': 'MEX',
             'micronesia' : 'FSM',
             'moldova': 'MDA',
             'monaco': 'MCO',
             'mongolia': 'MNG',
             'montenegro': 'MNE',
             'montserrat': 'GBR',
             'morocco': 'MAR',
             'mozambique': 'MOZ',
             'namibia': 'NAM',
             'nauru': "NRU",
             'nepal': 'NPL',
             'netherlands': 'NLD',
             'netherlands antilles': 'NLD',
             'new zealand': 'NZL',
             'nicaragua': 'NIC',
             'niger': 'NER',
             'nigeria' : 'NGA',
             'north korea': 'PRK',
             'norway': 'NOR',
             'oman': 'OMN',
             'pakistan': 'PAK',
             'palestine':'PAL',
             'palestinian territories': 'PAL',
             'panama': 'PAN',
             'papua new guinea': 'PNG',
             'paraguay': 'PRY',
             'peru': 'PER',
             'philippines': 'PHL',
             'pitcairn islands': 'NA',
             'poland': 'POL',
             'portugal': 'PRT',
             'qatar': 'QAT',
             'republic of congo': 'COG',
             'romania': 'ROU',
             'russia': 'RUS',
             'rwanda': 'RWA',
             'saint vincent and the grenadines': 'VCT',
             'samoa' : 'WSM',
             'sao tome and principe': 'STP',
             'saudi arabia': 'SAU',
             'senegal': 'SEN',
             'serbia': 'SRB',
             'serbia and montenegro': 'MNE',
             'seychelles': 'SYC',
             'sierra leone': 'SLE',
             'singapore': 'SGP',
             'slovakia': 'SVK',
             'slovenia': 'SVN',
             'solomon islands': 'SLB',
             'somalia': 'SOM',
             'south africa': 'ZAF',
             'south korea': 'KOR',
             'south sudan': 'SSD',
             'soviet union': 'RUS',
             'spain': 'ESP',
             'sri lanka': 'LKA',
             'st helena' : 'GBR',
             'st kitts and nevis' :'KNA',
             'st lucia': 'LCA',
             'st vincent': 'VCT',
             'sudan': 'SDN',
             'suriname': 'SUR',
             'swaziland': 'SWZ',
             'sweden': 'SWE',
             'switzerland': 'CHE',
             'syria': 'SYR',
             'taiwan': 'TWN',
             'tajikistan': 'TJK',
             'tanzania': 'TZA',
             'thailand': 'THA',
             'togo': 'TGO',
             'tonga': 'TON',
             'trinidad and tobago': 'TTO',
             'tunisia': 'TUN',
             'turkey': 'TUR',
             'turkmenistan': 'TKM',
             'turks and caicos islands': 'TCA',
             'uganda': 'UGA',
             'ukraine': 'UKR',
             'united arab emirates': 'ARE',
             'united kingdom': 'GBR',
             'united states of america': 'USA',
             'unknown' :'NA',
             'uruguay': 'URY',
             'uzbekistan': 'UZB',
             'vanuatu': 'VUT',
             'venezuela': 'VEN',
             'vietnam': 'VNM',
             'yemen': 'YEM',
             'yugoslavia': 'MNE',
             'zambia': 'ZMB',
             'zimbabwe': 'ZWE'}
